# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
                ('bus_name', models.CharField(max_length=255)),
                ('bus_city', models.TextField(max_length=100)),
                ('bus_address', models.CharField(max_length=255)),
                ('bus_category', models.TextField(max_length=255)),
            ],
        ),
    ]
