# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
