# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 00:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0002_auto_20171121_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 11, 22, 0, 56, 57, 728000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='images',
            field=models.ImageField(default=datetime.datetime(2017, 11, 22, 0, 57, 20, 487000, tzinfo=utc), upload_to=b''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
