# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0004_auto_20171121_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
