# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0005_business_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000, null=True)),
                ('rating', models.PositiveSmallIntegerField(null=True)),
                ('images', models.ImageField(null=True, upload_to=b'')),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='business',
            name='rating',
        ),
    ]
