# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0006_auto_20171122_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='business',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='business_app.Business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='PLACEHOLDER TEXT COMMENT/REVIEW', max_length=2000, null=True),
        ),
    ]
