# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('business_app', '0007_auto_20171122_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='login_app.User'),
            preserve_default=False,
        ),
    ]
